jsk-ros-pkg/jsk_model_tools

- euscollada/src/collada2eus.cpp
- euscollada/src/collada2eus_urdfmodel.cpp
this is for #99, now you can mark with 0.5.2, so this patch is just tempolary hack until then,
see https://github.com/jbeder/yaml-cpp/pull/296. I also changed collada2eus_urdfmodel, but 
it did not mean I approved this code, we need merge this into collada2eus.cpp, alway to keep
code compact, for future mentenance.
> [euscollada/src/collada2eus.cpp] super ugry hack untilyaml-cpp 0.5.2

- euscollada/src/collada2eus.cpp
docのメンバからNodeを作ったあとにNodeのサイズを確認するように変更をしました.
euscolladaのend-coordsの生成部分に関して, 現在はtranslate, rotateの記述がない場合docの該当メンバにアクセスした時点でExceptionが出ることを期待している実装になっているようですが,
yaml-cpp-0.5ではdocのメンバにアクセスした時点ではExceptionが出ず, nodeのインデックスにアクセスした段階でExceptionが出るようになっています.
したがって中途半端にend-coordsの部分のeusのコードが生成されてしまい, 括弧対応が取れず正しいeusのモデルファイルになりません.
> [euscollada] Add size check to end-coords translation/rotation

- euscollada/src/euscollada-robot.l
- euscollada/src/euscollada-robot_urdfmodel.l
Always make pqpmodel for detailed shape according to https://github.com/euslisp/jskeus/pull/232.b
> Always make pqpmodel for detailed shape

- euscollada/scripts/parseColladaBase.py
1. Force to use string. yaml parser automatically parse digit numbers as
integer or float. OTH, minidom parser always outputs everything in
string.
We force to convert yaml parser's output into string value.
2. Raise exception if there is no tag section.
3. Do not remove parent node if replaced_attribute_value syntax is used
> [euscollada] Fix replace_xmls syntax in add_sensor_to_collada.py

- euscollada/scripts/parseColladaBase.py
@garaemon さん
SampleRobotは
head-end-coordsを持っていますが，headに属する関節がないため，
add_sensor_to_collada.pyで以下のエラーが起きて，
このPRで直りました．
問題なさそうか確認お願いします．
```
[hrpsys_ros_bridge_tutorials] Traceback (most recent call last):
[hrpsys_ros_bridge_tutorials]   File "/home/leus/ros/hydro/src/jsk-ros-pkg/jsk_model_tools/euscollada/scripts/add_sensor_to_collada.py", line 45, in <module>
[hrpsys_ros_bridge_tutorials]     yaml_obj.replace_xmls(obj)
[hrpsys_ros_bridge_tutorials]   File "/home/leus/ros/hydro/src/jsk-ros-pkg/jsk_model_tools/euscollada/scripts/parseColladaBase.py", line 476, in replace_xmls
[hrpsys_ros_bridge_tutorials]     raise Exception("yaml does not have tag section")
[hrpsys_ros_bridge_tutorials] Exception: yaml does not have tag section
[hrpsys_ros_bridge_tutorials] make[2]: *** …
```
> [euscollada] return if limb key not found

- euscollada/src/collada2eus.cpp
https://github.com/euslisp/EusLisp/pull/139 にも関係するんですが、
verticesをN行３列 行列にしているんですが、Nが大きくなるとロード時間が
Nx3要素のfloat-vectorに比べて大幅に時間がかかることがわかりました。
なのでベクトルを読んでから行列に入れています。
これでjaxon_redのロード時間が半分くらいになります。
> Fix large matrix

- euscollada/src/euscollada-robot.l
merge after https://github.com/euslisp/jskeus/pull/270
> make qpqmodel with glvertices

- eusurdf/.gitignore
- eusurdf/CMakeLists.txt
- eusurdf/README.md
- eusurdf/cmake/eusurdf.cmake
- eusurdf/euslisp/eusscene_to_xacro.l
- eusurdf/package.xml
- eusurdf/scripts/urdf_to_xacro.py
- eusurdf/textured_models/apply_to_xacro.sh
- eusurdf/textured_models/room73b2-georgia-emerald-mountain/model.urdf.xacro
- eusurdf/textured_models/room73b2-hitachi-fiesta-refrigerator/model.urdf.xacro
- eusurdf/textured_models/room73b2-hitachi-fiesta-refrigerator_fixed/model.urdf.xacro
- eusurdf/textured_models/room73b2-hitachi-fiesta-refrigerator_static/model.urdf.xacro
- eusurdf/textured_models/room73b2-iemon/model.urdf.xacro
- eusurdf/textured_models/room73b2-mac-burger-box/model.urdf.xacro
- eusurdf/textured_models/room73b2-wanda/model.urdf.xacro
automatically generates urdf.xacro file for eus scene.
sample:
https://gist.github.com/f55fb768af9d73ad903fe1cdd94bb8b4
You can generate one urdf file for each scene and spawn with `rosrun gazebo_ros spawn_model` to gazebo.
```xml
<launch>
<arg name="model" default="/home/furushchev/ros/bremen/catkin_ws/src/jsk_model_tools/eusurdf/worlds/room73b2.urdf.xacro"/>
<param name="room73b2_description" command="$(find xacro)/xacro.py '$(arg model)'"/>
<node name="spawn_room73b2" pkg="gazebo_ros" type="spawn_model"
args="-param room73b2_description -urdf -model room73b2"/>
</launch>
```
> [eusurdf] generate urdf.xacro for model / scene

- eusurdf/euslisp/eusmodel_to_urdf.l
- eusurdf/euslisp/eusscene_to_world.l
- eusurdf/euslisp/eusscene_to_xacro.l
To fix error on overwrite behavior of model generation
```lisp
(with-open-file (f "test.txt" :direction :output :if-exists :overwrite)
(format f "1~%2~%3~%"))
(with-open-file (f "test.txt" :direction :output :if-exists :overwrite)
(format f "4~%5~%"))
```
I expected this results:
```
4
5
```
but this outputs
```
4
5
3
```
> [eusurdf] fix: use :if-exists :new-version instead of :overwrite

- eusurdf/package.xml
fix http://build.ros.org/view/Kbin_uX64/job/Kbin_uX64__eusurdf__ubuntu_xenial_amd64__binary/1/console
> add python-lxml to run_depends

- .travis.yml
- eus_assimp/package.xml
- eus_assimp/src/eus_assimp.cpp
failing on build firm : http://build.ros.org/view/Ksrc_uX/job/Kbin_uX64__eus_assimp__ubuntu_xenial_amd64__binary/
c.f. https://github.com/euslisp/EusLisp/pull/300
> since euslisp 9.25.0, we need to add 5 arguments including doc string with defun()

- euscollada/src/euscollada-robot.l
-  ```:def-gl-vertices``` was only used by collada2eus.org
-  origin of glvertices should be origin of link. At former version, origin of glvertises and link was the same. So, we could not find out this bug.
> [euscollada] fix collision model for version 0.4.0

- eusurdf/CMakeLists.txt
aptで入るパッケージでも、eusからurdfへの変換を行えるようにしたいため、eusのディレクトリも追加しました。
> [eusurdf] add euslisp to INSTALL_DIRS

- euscollada/CMakeLists.txt
- euscollada/pr2-mimic.sh
- euscollada/pr2-mimic.yaml
- euscollada/src/collada2eus_urdfmodel.cpp
- euscollada/src/euscollada-robot.l
- euscollada/test/euscollada-model-conversion-test.l
- euscollada/test/robots/test-linear-1.urdf
- euscollada/test/robots/test-linear-1.yaml
- euscollada/test/robots/test-linear-mimic-1.urdf
- euscollada/test/robots/test-linear-mimic-1.yaml
- euscollada/test/robots/test-linear-mimic-2.urdf
- euscollada/test/robots/test-linear-mimic-2.yaml
- euscollada/test/robots/test-revolute-1.urdf
- euscollada/test/robots/test-revolute-1.yaml
- euscollada/test/robots/test-revolute-2.urdf
- euscollada/test/robots/test-revolute-2.yaml
- euscollada/test/robots/test-revolute-mimic-1.urdf
- euscollada/test/robots/test-revolute-mimic-1.yaml
- euscollada/test/robots/test-revolute-mimic-2.urdf
- euscollada/test/robots/test-revolute-mimic-2.yaml
- euscollada/test/robots/test-revolute-mimic-3.urdf
- euscollada/test/robots/test-revolute-mimic-3.yaml
- euscollada/test/robots/test-revolute-mimic-4.urdf
- euscollada/test/robots/test-revolute-mimic-4.yaml
- euscollada/test/robots/test-revolute-mimic-5.urdf
- euscollada/test/robots/test-revolute-mimic-5.yaml
- euscollada/test/test-mimic.l
- euscollada/test/test-mimic.test
add mimic-joint-params, rotational-mimic-joint linear-mimic-joint class
see `pr2-mimic.sh` for exmaple, it generate codes as follows;
```
;; re-define r_gripper_l_finger_joint as mimic-joint
(let (tmp-mimic-joint)
(setq tmp-mimic-joint (replace-object (instance rotational-mimic-joint :init :parent-link (make-cascoords) :child-link (make-cascoords) :max-joint-velocity 0 :max-joint-torque 0) r_gripper_l_finger_joint_jt))
(setq r_gripper_l_finger_joint_jt tmp-mimic-joint))
(setq (r_gripper_l_finger_joint_jt . mimic-joints)
(list
(instance mimic-joint-param :init r_gripper_l_finger_tip_joint_jt :multiplier 1.000000 :offset 0.000000)
(instance mimic-joint-param :init r_gripper_r_finger_joint_jt :multiplier 1.000000 :offset 0.000000)
(instance mimic-joint-param :init …
```
> add mimic joint support for collada2eus

- eusurdf/README.md
The function `irteus2urdf-room-for-gazebo` requires the [parameter](https://github.com/jsk-ros-pkg/jsk_model_tools/blob/1a46176495c7f8cd3c3483f560072093ec2673ad/eusurdf/euslisp/convert-eus-to-urdf.l#L47), however it didn't write on the readme and this code won't work. So I add the parameter.
> add world-file-path on README

- euscollada/pr2_custom_limb.yaml
- euscollada/src/collada2eus_urdfmodel.cpp
- euscollada/test/euscollada-model-conversion-test.l
- euscollada/test/samplerobot1.yaml
- euscollada/test/samplerobot2.yaml
https://github.com/jsk-ros-pkg/jsk_model_tools/pull/249 に、
- 複数yamlを読み込む機能
- replace_xmlsなどのキーをlimbと誤って解釈しないようにする修正
を追加しました。
> enable to read custom limb name from .yaml file (fix for #249)

- euscollada/src/collada2eus_urdfmodel.cpp
this is another imlimentation for supporting non-default limbs, https://github.com/jsk-ros-pkg/jsk_model_tools/pull/232
if the limb name is other than head,torso,larm,rarm,lleg,rleg, we set limb name to robot models. So this does not require newer EusLisp/jskeus.
> enable to read custom limb name from .yaml file

- euscollada/src/collada2eus_urdfmodel.cpp
https://github.com/jsk-ros-pkg/jsk_model_tools/pull/250#issuecomment-1510515482 に対応したPull Requestです。
これまで、collada2eusのソースコードに変更を加える度に、生成されるeusモデルのリンクの宣言順が変わってしまって、生成されるeusモデルに大きなdiffが発生してしまい、collada2eusに加えた変更が妥当かどうかの検証がしづらい、という問題が有りました。
考えられる原因は、次のとおりです。
collada2eusは、https://github.com/jsk-ros-pkg/jsk_model_tools/blob/6749740bdb803cdaeb4d453e086b805f05b6c030/euscollada/src/collada2eus_urdfmodel.cpp#L777-L781 やhttps://github.com/jsk-ros-pkg/jsk_model_tools/blob/6749740bdb803cdaeb4d453e086b805f05b6c030/euscollada/src/collada2eus_urdfmodel.cpp#L1862-L1866 で、linkのshared_ptrをキーとするmapにlinkが格納されていて、mapのイテレータを回したときにどのような順番になっているかによって、linkの宣言順番が決まっています。mapのイテレータの順番は、デフォルトだと恐らくlinkのアドレス順になるので、linkのメモリを確保するときにどのアドレスに確保されたかに依存すると思われます。そのため、collada2eusのソースコードに変更を加えると、変更した部分で行うメモリ確保・開放がlinkのアドレスに何らかの影響を …
> [collada2eus_urdfmodel.cpp] print links in the order of link names

- euscollada/scripts/add_sensor_to_collada.py
- euscollada/scripts/parseColladaBase.py
- euscollada/scripts/replace_library_nodes.py
@pazeshun will fix this PR to work with Python 2, too.
> [DO NOT MERGE] fixed some scripts for python3

- eusurdf/CMakeLists.txt
follow up to https://github.com/jsk-ros-pkg/jsk_model_tools/pull/262
models/worlds directory is auto-generatied only when gazebo_ros package exists
> install models/worlds directory only when gazebo_ros_FOUND
