euscollada/scripts/add_sensor_to_collada.py, euscollada/scripts/parseColladaBase.py
update parseColladaBase.py and add_sensor_to_collada.py for handling urdf file
=> update scripts for robot_models

euscollada/scripts/urdf_patch.py
* Support urdf file which has a joint without xyz and rpy tags
* Output patched urdf to standard output
=> [euscollada] Update urdf_patch.py to handle joint without xyz and rpy tag and to output patched urdf to standard output

eus_assimp/euslisp/eus-assimp.l
you  can use (save-mesh-file "mesh.wrl" object_glvertices)
=> add dump-glvertices-to-wrl for creating wrl mesh file from glvertices

eusurdf/euslisp/convert-eus-to-urdf.l
solve https://github.com/jsk-ros-pkg/jsk_model_tools/issues/124 .
=> [eusurdf] generate random tmp directory to avoid overwrite

eus_assimp/euslisp/eus-assimp.l
https://github.com/euslisp/jskeus/pull/144
=> move functions to jskeus

euscollada/CMakeLists.txt
=> [euscollada] Compare rosversion using its alphabetical order to deal with jade

euscollada/src/collada2eus.cpp, euscollada/src/collada2eus_urdfmodel.cpp, euscollada/src/euscollada-robot.l, euscollada/src/euscollada-robot_urdfmodel.l
=> use changes for using glbody in irtgl.l

.travis.yml
Please wait for https://github.com/jsk-ros-pkg/jsk_travis/pull/102 to be merged
and submodules to be updated.
=> Add travis test for ROS jade

euscollada/src/euscollada-robot.l, euscollada/src/euscollada-robot_urdfmodel.l
Add arugment to use 6dof-joint leg weighing for evaluate the influence with it and without it.
=> Add arugment to use 6dof-joint leg weighing for evaluate the influence with it and without it.

euscollada/src/euscollada-robot.l
use-6dof-joint-leg-gain nil by default.
=> use-6dof-joint-leg-gain nil by default.

eusurdf/models/.gitignore, eusurdf/models/manifest.xml, eusurdf/scripts/eus2urdf_for_gazebo.py
manifest.xml in gazebo model directory is not necessary now.
cc: @wkentaro
=> [eusurdf] delete manifest.xml for gazebo model directory

euscollada/src/collada2eus.cpp, euscollada/src/collada2eus_urdfmodel.cpp, euscollada/src/euscollada-robot.l
https://github.com/jsk-ros-pkg/jsk_model_tools/pull/131
この問題が解消するかと思います。
=> keep backward compatibility, add glvertices slot to collada-body

eusurdf/package.xml
@mmurooka
http://jenkins.ros.org/job/ros-indigo-eusurdf_binarydeb_trusty_amd64/18/console
=> package.xml; we nee do rosrun to generate models

eusurdf/euslisp/convert-eus-to-urdf.l, eusurdf/euslisp/generate-model-from-voxel.l
=> [eusurdf] add script to generate eus cube list from voxel

eusurdf/package.xml, eusurdf/scripts/convert-scene-to-urdf.py
https://github.com/jsk-ros-pkg/jsk_model_tools/pull/163 is contained in this PR.
ー add roseus to run_depend.
ー use environment variable to get eusdir.
ー call roseus without rosrun.
=> [eusurdf] fix for deb package build

euscollada/src/collada2eus_urdfmodel.cpp
Fix location of gl::vertices setting.
Move after geom is set.
@YoheiKakiuchi
=> Fix location of gl::vertices setting

euscollada/src/collada2eus.cpp
Modified:
- euscollada/src/collada2eus.cpp
=> [euscollada] Support passing limbs to predefined pose method

eusurdf/CMakeLists.txt, eusurdf/euslisp/convert-eus-to-urdf.l, eusurdf/package.xml, eusurdf/test/convert-eus-to-urdf-test.l, eusurdf/test/convert-eus-to-urdf-test.launch
https://github.com/jsk-ros-pkg/jsk_model_tools/pull/169#issuecomment-217141539
=> [eusurdf] add test of model conversion

euscollada/src/collada2eus.cpp
a open file should be closed.
when there are many open files, file open error will occur.
=> [collada2eus] fix closing /dev/null

euscollada/CMakeLists.txt, euscollada/package.xml, euscollada/src/euscollada-robot.l, euscollada/test/euscollada-model-conversion-test.l, euscollada/test/euscollada-model-conversion.test, euscollada/test/samplerobot.yaml, euslisp_model_conversion_tester/euslisp/model-inertia-check.l
fix failure in https://github.com/jsk-ros-pkg/jsk_model_tools/pull/191
=> Fix conversion of mass properties

eusurdf/.gitignore, eusurdf/README.md, eusurdf/cmake/eusurdf.cmake, eusurdf/euslisp/convert-eus-to-urdf.l, eusurdf/euslisp/eusscene_to_xacro.l, eusurdf/launch/gazebo_spawn_scene.launch, eusurdf/scripts/urdf_to_xacro.py, eusurdf/textured_models/room73b2-georgia-emerald-mountain/model.urdf.xacro, eusurdf/textured_models/room73b2-hitachi-fiesta-refrigerator/model.urdf.xacro, eusurdf/textured_models/room73b2-hitachi-fiesta-refrigerator_fixed/model.urdf.xacro, eusurdf/textured_models/room73b2-hitachi-fiesta-refrigerator_static/model.urdf.xacro, eusurdf/textured_models/room73b2-iemon/model.urdf.xacro, eusurdf/textured_models/room73b2-mac-burger-box/model.urdf.xacro, eusurdf/textured_models/room73b2-wanda/model.urdf.xacro
to keep compatibility with ros system (ros node cannot resolve mesh path from `model://` directive.)
=> [eusurdf] use package://eusurdf instead of model://

eus_assimp/CMakeLists.txt, eusurdf/cmake/eusurdf.cmake
this should fix
- http://build.ros.org/job/Kbin_djv8_dJv8__eus_assimp__debian_jessie_arm64__binary/
- http://build.ros.org/job/Kbin_djv8_dJv8__eusurdf__debian_jessie_arm64__binary/
=> Fix for arm processor

euscollada/CMakeLists.txt, euscollada/pr2.sh
=> fix to run installed euscollada

.travis.yml, euscollada/test/euscollada-model-conversion-test.l
*    fix timeout for reading stream
*    set origin of robot before comparing centroid
=> [euscollada] fix test

collada_tools/src/collada_to_urdf.cpp, eusurdf/textured_models/room73b2-hitachi-fiesta-refrigerator/model.urdf, eusurdf/textured_models/room73b2-hitachi-fiesta-refrigerator_fixed/model.urdf, eusurdf/textured_models/room73b2-hitachi-fiesta-refrigerator_static/model.urdf
rebased version of #183
Closes #183
=> Fix for being deprecated tag: cfmDamping -> implicitSpringDamper

euscollada/src/collada2eus_urdfmodel.cpp
`use_simple_geometry` was introduced in https://github.com/jsk-ros-pkg/jsk_model_tools/commit/6bc87f3eb61c82106c7e9bf14a02a5e819226932, but not implemented ?
original version : 
```
$ ls -al unitreeeus/go1.l
-rw-rw-r-- 1 k-okada k-okada 57518932 Apr  1 14:40 unitreeeus/go1.l
$ time irteusgl unitreeeus/go1.l '(exit)'
real	0m3.116s
user	0m3.038s
sys	0m0.072s
```
with `--simple_geometry`, 
```
$ ls -al unitreeeus/go1.l
-rw-rw-r-- 1 k-okada k-okada 201K Apr 21 18:44 unitreeeus/go1.l
$ time irteusgl unitreeeus/go1.l '(exit)'
real	0m0.151s
user	0m0.149s
sys	0m0.000s
```
c.f. examples
https://github.com/k-okada/jsk_robot/blob/f7a50a0e8c1b07d6b059c182ea254ed10cd8d21e/jsk_unitree_robot/unitreeeus/CMakeLists.txt#L48-L51
=> support use_simple_geometry, with bounding box

euscollada/scripts/add_sensor_to_collada.py, euscollada/scripts/parseColladaBase.py, euscollada/scripts/replace_library_nodes.py
PR for https://github.com/jsk-ros-pkg/jsk_model_tools/pull/251#issuecomment-1902903634
=> fix for python3 python2 compatible

euscollada/scripts/add_eef_to_urdf.py, euscollada/scripts/parseColladaBase.py, euscollada/scripts/urdf_patch.py
update python scripts for hrpsys_ros_bridge_tutorials in Noetic. `catkin build hrpsys_ros_bridge_tutorials` has passed successfully.
=> [WIP] [euscollada] update for Noetic

.github/workflows/config.yml, .github/workflows/rosdep-24.04.yaml, euscollada/CMakeLists.txt, eusurdf/CMakeLists.txt, urdf_mesh_converter/requirements.in
CI: add ROS-O 24.04@techfak setting
=> add test to check #260
